test:
  db_hostname:
  db_username:
  db_password:
  db_name:

  app_hostname:
  app_port:
  app_base_domain:

  mailer_from_address:

  devise_secret_key:
  devise_pepper_hash:
  
  REDIS_URL:

  encrypt_key:


development:
  db_hostname:
  db_username:
  db_password:
  db_name:

  app_hostname:
  app_port:
  app_base_domain:
  
  mailer_from_address:

  devise_secret_key:
  devise_pepper_hash:

  REDIS_URL:

  encrypt_key:

production:
  db_hostname:
  db_username:
  db_password:
  db_name:

  app_hostname:
  app_port:
  app_base_domain:
  
  mailer_from_address:

  devise_secret_key:
  devise_pepper_hash:

  REDIS_URL:

  encrypt_key: