test:
  db_hostname:
  db_username:
  db_password:
  db_name:

  app_hostname:
  app_port:
  app_base_domain:
  c_name:
  admin_username:

  mailer_from_address:
  
  sendgrid_api_key:
  sendgrid_domain:

  devise_secret_key:
  devise_pepper_hash:
  
  REDIS_URL:

  encrypt_key:

  content_moderation_url:
  content_moderation_api_key:

  ci_true:


development:
  db_hostname:
  db_username:
  db_password:
  db_name:

  app_hostname:
  app_port:
  app_base_domain:
  c_name:
  admin_username:
  
  mailer_from_address:
  
  sendgrid_api_key:
  sendgrid_domain:

  devise_secret_key:
  devise_pepper_hash:

  REDIS_URL:

  encrypt_key:

  content_moderation_url:
  content_moderation_api_key:


production:
  db_hostname:
  db_username:
  db_password:
  db_name:

  app_hostname:
  app_port:
  app_base_domain:
  c_name:
  admin_username:
  
  mailer_from_address:
  
  sendgrid_api_key:
  sendgrid_domain:

  devise_secret_key:
  devise_pepper_hash:

  REDIS_URL:

  encrypt_key:

  content_moderation_url:
  content_moderation_api_key: