# MySQL Versions 5.5.8 and up are supported.

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock
  host: <%= ENV["db_hostname"] %>
  username: <%= ENV["db_username"] %>
  password: <%= ENV["db_password"] %>

development:
  <<: *default
  database: <%= ENV["db_name"] %>

# Do not set this db to the same as development or production.
test:
  <<: *default
  database: <%= ENV["db_name"] %>

# You can use this database configuration with:
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
production:
  <<: *default
  database: <%= ENV["db_name"] %>